[package]
name = "central"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "central-server"
path = "src/bin/server.rs"

[lib]
name = "ethoko_central"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.102"
argon2 = "0.5.3"
askama = { version = "0.16.0", default-features = false, features = ["std", "derive"] }
async-trait = "0.1.89"
axum = { version = "0.8.9", features = ["macros"] }
base64 = "0.22.1"
chrono = { version = "0.4.44", features = ["serde"] }
dotenvy = "0.15.7"
fake = { version = "5.1.0", features = ["chrono"] }
governor = "0.10.0"
reqwest = { version = "0.13.3", features = ["json", "blocking"] }
resend-rs = "0.30.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.11.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "uuid", "chrono"] }
thiserror = "2.0.18"
tokio = { version = "1.52.1", features = ["full"] }
tokio-util = "0.7.18"
tower-http = { version = "0.6.8", features = ["trace", "timeout", "request-id"] }
tower_governor = { version = "0.8.0", features = ["tracing", "axum"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
uuid = { version = "1.23.1", features = ["v4", "serde"] }
validator = "0.20.0"
