import { HardhatRuntimeEnvironment } from "hardhat/types";
import { DeployFunction } from "hardhat-deploy/types";
import { project } from "../.soko-typings";

/**
 * This deployment script deploys the Counter contract targeting a specific release.
 *
 * The compilation artifacts are retrieved from the Soko project registry for the specified release.
 * The artifacts are **frozen** at the time of the release, ensuring consistent deployments.
 * Local modifications to the contract source code or any new compilation, releases etc.. will not affect this deployment.
 *
 * The `Counter` contract is deployed first.
 * The deployment is done using `hardhat-deploy@v0.12`.
 *
 * This script relies on typings generated by Soko for the project "dummy-counter".
 * It is assumed that the tag `2026-02-04` exists in the Soko registry for this project.
 * It could have been created by running:
 * ```
 * npx hardhat soko push --tag 2026-02-04 --artifact-path ./artifacts
 * ```
 * The assumed commands that have been run prior to this deployment are:
 *  - `npx hardhat soko pull` to pull the project from the Soko registry,
 *  - `npx hardhat soko typings` to generate the typings for the project.
 */

const TARGET_RELEASE = "2026-02-04";

const deployCounter: DeployFunction = async function (
  hre: HardhatRuntimeEnvironment,
) {
  const { deployer } = await hre.getNamedAccounts();

  const balance = await hre.ethers.provider.getBalance(deployer);

  console.log("Deploying contracts with account: ", {
    address: deployer,
    balance: hre.ethers.formatEther(balance),
  });

  // Get project utilities for the target release
  const projectUtils = project("dummy-counter").tag(TARGET_RELEASE);

  // Get the `Counter` artifact for the target release and deploy it
  const counterArtifact = await projectUtils.getContractArtifact(
    "src/Counter.sol:Counter",
  );
  await hre.deployments.deploy(`Counter@${TARGET_RELEASE}`, {
    contract: {
      abi: counterArtifact.abi,
      bytecode: counterArtifact.evm.bytecode.object,
      metadata: counterArtifact.metadata,
    },
    from: deployer,
    log: true,
  });
};

export default deployCounter;
